#! /usr/bin/env bash

# Using awk to parse ...
# jo b                  == json.color b
# jo b=[1,2,3]          == json.var b [1,2,3]
# jo b.hi.c=5           == json.putkv
# jo b.append(3)        == json.append b 3
# jo b.push(3)          == json.push b 3
# jo b.prepend(3)       == json.prepend b 3
# jo b.shift()          == json.shift b
# jo b.pop()            == json.pop b
# jo b.values()         == json.values b


# This kind of code should be placed in to the 
jo(){
    :
    case $# in
    0)  echo "show help";;
    1)  
        [[ "$1" =~ ^[A-Za-z_0-9]$ ]] && jo.color "$1" && break;
        # TODO
        [[ "$1" =~ ^[A-Za-z_0-9]= ]] && jo.var "${1%%=*}" "${1#*=}" && break;
        [[ "$1" =~ ^[A-Za-z_0-9.\[\]\*]= ]] && jo.putkv "${1%%=*}" "${1#*=}" && break;

        jo.query "$1" ;;
    2);;
    *);;
    esac
}
