#! /usr/bin/env bash

# JSON_AWK_PATH="$(xrc.which json/json_walk.awk)"
JSON_AWK_PATH="./json_walk.awk"
json.var(){
    local varname=${1:?Provide variable name} s
    shift
    if [ $# -ne 0 ]; then
        s="$(awk -f "$JSON_AWK_PATH" <<<"$@")"
    else
        s="$(awk -f "$JSON_AWK_PATH" -)"
    fi
    local code=$?
    if [ $code -eq 0 ]; then eval "$varname=\"\$s\""
    else return 1;  fi
}

json.color(){
    if [ "$1" ]; then
        local varname=${1:?Provide variable name} s
        awk -v format=1 -v color=1 -f "$JSON_AWK_PATH" <<<"${!varname}"
    else
        awk -v format=1 -v color=1 -f "$JSON_AWK_PATH" -
    fi
}

# aaa.push()
json.push(){ json.append "$@"; }

# aaa.append()
json.append(){
    local keypath=${1:?Provide variable name} opv1 opv2="${2:?Provide value}" varname s

    varname=${keypath%%.*}
    opv1=".${keypath#*.}"
    [ "$varname" == "$keypath" ] && opv1="."
    shift 2
    
    if [ "$varname" ]; then
        s="$(awk -v op=append -v opv1="$opv1" -v opv2="$opv2" -f "$JSON_AWK_PATH" <<<"${!varname}")"
    else
        s="$(awk -v op=append -v opv1="$opv1" -v opv2="$opv2" -f "$JSON_AWK_PATH")"
    fi
    local code=$?
    if [ $code -eq 0 ]; then eval "$varname=\"\$s\""
    else return 1;  fi
}

# aaa.prepend("value")
json.prepend(){
    local keypath=${1:?Provide variable name} opv1 opv2="${2:?Provide value}" varname s

    varname=${keypath%%.*}
    opv1=".${keypath#*.}"
    [ "$varname" == "$keypath" ] && opv1="."
    shift 2
    
    if [ "$varname" ]; then
        s="$(awk -v op=prepend -v opv1="$opv1" -v opv2="$opv2" -f "$JSON_AWK_PATH" <<<"${!varname}")"
    else
        s="$(awk -v op=prepend -v opv1="$opv1" -v opv2="$opv2" -f "$JSON_AWK_PATH")"
    fi
    local code=$?
    if [ $code -eq 0 ]; then eval "$varname=\"\$s\""
    else return 1;  fi
}

# jo b.b= 2

: <<"DOCTEST"
> b={a:1}
> json.put b.b 2
> echo "$b"
DOCTEST
json.put(){
    local keypath=${1:?Provide variable name} opv1 opv2="${2:?Provide value}" varname s

    varname=${keypath%%.*}
    opv1=".${keypath#*.}"
    [ "$varname" == "$keypath" ] && opv1="."
    shift 2
    
    if [ "$varname" ]; then
        s="$(awk -v op=put -v opv1="$opv1" -v opv2="$opv2" -f "$JSON_AWK_PATH" <<<"${!varname}")"
    else
        s="$(awk -v op=put -v opv1="$opv1" -v opv2="$opv2" -f "$JSON_AWK_PATH")"
    fi
    local code=$?
    if [ $code -eq 0 ]; then eval "$varname=\"\$s\""
    else return 1;  fi
}

# jo b.b
: <<"DOCTEST"
> b=[1,2,3]
> json.values b
1
2
3
DOCTEST
json.values(){
    local keypath=${1:?Provide variable name} opv1 varname s

    varname=${keypath%%.*}
    opv1=".${keypath#*.}"
    [ "$varname" == "$keypath" ] && opv1=""
    shift 2
    
    if [ "$varname" ]; then
        awk -v op=values -v opv1="$opv1" -f "$JSON_AWK_PATH" <<<"${!varname}"
    else
        awk -v op=values -v opv1="$opv1" -f "$JSON_AWK_PATH"
    fi
}

# jo b.b
json.query(){
    local keypath=${1:?Provide variable name} opv1 varname s

    varname=${keypath%%.*}
    opv1=".${keypath#*.}"
    [ "$varname" == "$keypath" ] && opv1="."
    shift 2

    if [ "$varname" ]; then
        awk -v op=extract -v opv1="$opv1" -f "$JSON_AWK_PATH" <<<"${!varname}"
    else
        awk -v op=extract -v opv1="$opv1" -f "$JSON_AWK_PATH" -
    fi
}

: <<"DOCTEST"
> b=[1,2,3]
> json.del b.[0]
> echo $b
[2,3]
DOCTEST
json.del(){
    local keypath=${1:?Provide variable name} opv1 varname s

    varname=${keypath%%.*}
    opv1=".${keypath#*.}"
    [ "$varname" == "$keypath" ] && opv1="."
    shift 2
    
    if [ "$varname" ]; then
        s="$(awk -v op=del -v opv1="$opv1" -f "$JSON_AWK_PATH" <<<"${!varname}")"
    else
        s="$(awk -v op=del -v opv1="$opv1" -f "$JSON_AWK_PATH")"
    fi
    local code=$?
    if [ $code -eq 0 ]; then eval "$varname=\"\$s\""
    else return 1;  fi
}

: <<"DOCTEST"
> b=[1,2,3]
> json.shift b
> echo $b
[2,3]
DOCTEST
json.shift(){
    local keypath=${1:?Provide variable name} opv1 varname s

    varname=${keypath%%.*}
    opv1=".${keypath#*.}"
    [ "$varname" == "$keypath" ] && opv1="."
    shift 2
    
    if [ "$varname" ]; then
        s="$(awk -v op=shift -v opv1="$opv1" -f "$JSON_AWK_PATH" <<<"${!varname}")"
    else
        s="$(awk -v op=shift -v opv1="$opv1" -f "$JSON_AWK_PATH")"
    fi
    local code=$?
    if [ $code -eq 0 ]; then eval "$varname=\"\$s\""
    else return 1;  fi
}

: <<"DOCTEST"
> b=[1,2,3]
> json.length b
3
DOCTEST
json.length(){
    local keypath=${1:?Provide variable name} opv1 varname s

    varname=${keypath%%.*}
    opv1=".${keypath#*.}"
    [ "$varname" == "$keypath" ] && opv1="."
    shift 2
    
    if [ "$varname" ]; then
        awk -v op=length -v opv1="$opv1" -f "$JSON_AWK_PATH" <<<"${!varname}"
    else
        awk -v op=length -v opv1="$opv1" -f "$JSON_AWK_PATH"
    fi
}

: <<"DOCTEST"
> b=[1,2,3]
> json.pop b
> echo $b
[2,3]
DOCTEST
json.pop(){
    local keypath=${1:?Provide variable name} opv1 varname s

    varname=${keypath%%.*}
    opv1=".${keypath#*.}"
    [ "$varname" == "$keypath" ] && opv1="."
    shift 2
    
    if [ "$varname" ]; then
        s="$(awk -v op=pop -v opv1="$opv1" -f "$JSON_AWK_PATH" <<<"${!varname}")"
    else
        s="$(awk -v op=pop -v opv1="$opv1" -f "$JSON_AWK_PATH")"
    fi
    local code=$?
    if [ $code -eq 0 ]; then eval "$varname=\"\$s\""
    else return 1;  fi
}

json.array(){
    local s=
    while [ $# -gt 0 ]; do
        case "$1" in
            true|false|null)    s="$s,$1"   ;;
            [*)                s="$s,$1";;
            \{*)              s="$s,$1";;
            # =\"*)             s="$2,${1:1}"   ;;
            *)  if [[ "$1" =~ ^[+-]?[0-9]+(.[0-9]+)*([eE][0-9]+(.[0-9]+))*$ ]];       
                then s="$s,$1" ;
                else s="$s,\"${1//\"/\\\"}\"" ;
                fi
                ;;
        esac
        shift
    done
    echo "[${s:1}]"
}

json.escape(){
    local a="${1:?Provide string}"
    a="$(echo "${a//$'\\'/\\}")"
    a="$(echo "${a//$'\n'/\\n}")"
    a="$(echo "${a//$'\t'/\\t}")"
    a="$(echo "${a//$'\b'/\\b}")"
    a="$(echo "${a//\"/\\\"}")"
    echo "\"$a\""
}

json.unescape(){
    if [ $# -gt 0 ]; then
        eval echo "$@"
    else
        while read -r line; do
            eval echo -e "$line"
        done
    fi
}

# Reference: https://github.com/jpmens/jo/blob/master/jo.md
json.dict(){
    printf "{\n"

    local key value
    local first=0
    for i in "$@"; do
        if [ "$first" -eq 0 ]; then
            first=1
        else
            printf ',\n'
        fi

        key=${i%%=*}
        if [ "$key" != "$i" ]; then
            value=${i#*=}

            case "$value" in
            true|false|null|\{*\}|\[*\]|\"*)
                printf '  %s: %s' "$(json.escape "$key")" "$value" ;;
            *)
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)*([eE][0-9]+(.[0-9]+))*$ ]]; then
                    printf '  %s: %s' "$(json.escape "$key")" "$value"
                else
                    printf '  %s: %s' "$key" "$(json.escape "$value")"
                fi
            esac
            continue
        fi

        key=${i%%\:*}
        value=${i#*\:}
        printf '  %s: %s' "$(json.escape "$key")" "$(json.escape "$value")"
    done
    printf "\n}"
}

json.dict.compact(){
    printf "{"

    local key value
    local first=0
    for i in "$@"; do
        if [ "$first" -eq 0 ]; then
            first=1
        else
            printf ','
        fi

        key=${i%%=*}
        if [ "$key" != "$i" ]; then
            value=${i#*=}

            case "$value" in
            true|false|null|\{*\}|\[*\]|\"*)
                printf '%s:%s' "$(json.escape "$key")" "$value" ;;
            *)
                if [[ "$value" =~ ^[+-]?[0-9]+(.[0-9]+)*([eE][0-9]+(.[0-9]+))*$ ]]; then
                    printf '%s:%s' "$(json.escape "$key")" "$value"
                else
                    printf '%s:%s' "$key" "$(json.escape "$value")"
                fi
            esac
            continue
        fi

        key=${i%%\:*}
        value=${i#*\:}
        printf '%s: %s' "$(json.escape "$key")" "$(json.escape "$value")"
    done
    printf "}"
}


# Scheme 1:
# out_color_key = "\033[0;35m"
# out_color_string = "\033[0;34m"
# out_color_number = "\033[0;32m"
# out_color_null = "\033[0;33m"   # "\033[0;31m"
# out_color_true = "\033[7;32m"
# out_color_false = "\033[7;31m"

# Scheme 2:
# out_color_key = "\033[1;34m"
# out_color_string = "\033[0;33m"
# out_color_number = "\033[1;35m"
# out_color_null = "\033[0;31m"
# out_color_true = "\033[7;32m"
# out_color_false = "\033[7;31m"

# Scheme 3:
# out_color_key = "\033[1;33m"
# out_color_string = "\033[0;34m"
# out_color_number = "\033[0;35m"
# out_color_null = "\033[0;31m"
# out_color_true = "\033[7;32m"
# out_color_false = "\033[7;31m"

json.awk.color1(){
    local IFS=$' '
    A=(
    -v out_color_key="\033[0;35m"
    -v out_color_string="\033[0;34m"
    -v out_color_number="\033[0;32m"
    -v out_color_null="\033[0;33m"
    -v out_color_true="\033[7;32m"
    -v out_color_false="\033[7;31m"
    )
    echo "${A[*]}"
}

# TODO: Using JSON
json.table(){
    local n="${1:?Provide colume number}"
    shift
    local arr=() final=() idx=0 line IFS

    if [ $# -gt 0 ]; then
        for line in "$@"; do
            (( idx ++ ))
            arr+=("$line")
            if [ "$idx" -eq "$n" ]; then
                final+=("$(json.array "${arr[@]}")")
                arr=()
                idx=0
            fi
            
        done
    else
        while read -r line; do
            (( idx ++ ))
            arr+=("$line")
            if [ "$idx" -eq "$n" ]; then
                final+=("$(json.array "${arr[@]}")")
                arr=()
                idx=0
            fi
        done
    fi
    json.array "${final[@]}"
}

json.attrlist(){
    local arr=() final=() idx=0 line IFS

    while read -r line; do
        (( idx ++ ))
        arr+=("${!idx}=$line")
        if [ "$idx" -eq "$#" ]; then
            final+=("$(json.dict "${arr[@]}")")
            arr=()
            idx=0
        fi
    done

    json.array "${final[@]}"
}

